from django.db import models


class RecommendationRequest(models.Model):
    # Basic user input fields
    age = models.IntegerField()
    category = models.CharField(max_length=100)
    previous_score = models.FloatField()

    # Output generated by the ML model
    recommendation_score = models.FloatField()

    # Automatically store when the request was created
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Helpful string representation in Django admin
        return f"Request {self.id} - {self.category}"